#Profile
spring.profiles.active=dev
spring.profiles.default=dev

# Server Port
server.port=8081

#Spring config
spring.application.name=@project.artifactId@

#Logging
logging.level.br.gov.am.prodam=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.root=INFO
logging.pattern.console= %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n

# Datasource configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@oradds1.prodam.am.gov.br:1521/oradds.prodam.com.br
spring.datasource.username=${USER:transito}
spring.datasource.password=${PASSWORD:tran8647}
spring.datasource.hikari.connectionInitSql=SELECT 1 FROM DUAL
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialiect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.open-in-view=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.encoding=utf-8

# Page configuration
spring.data.web.pageable.size-parameter=${PAGE_SIZE:20}
spring.data.web.pageable.page-parameter=${PAGE_NUMBER:100}
spring.data.web.pageable.default-page-size=${DEFAULT_PAGE_SIZE:20}
spring.data.web.pageable.one-indexed-parameters=${ONE_INDEXED:false}
spring.data.web.pageable.max-page-size=${MAX_PAGE_SIZE:2000}
spring.data.web.pageable.prefix=${PAGE_PREFIX:}
spring.data.web.pageable.qualifier-delimiter=${QUALIFIER_DELIMITER:_}

# to fix Swagger 3 problem
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#Spring Actuator
management.endpoints.web.exposure.include=*

# Redis
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=7

# Keycloak
spring.security.oauth2.client.provider.external.issuer-uri=http://localhost:8080/realms/external

spring.security.oauth2.client.registration.external.provider=external
spring.security.oauth2.client.registration.external.client-name=external-client
spring.security.oauth2.client.registration.external.client-id=external-client
spring.security.oauth2.client.registration.external.client-secret=${CLIENT_SECRET:4bb6d5d2-2694-49eb-ab16-7094afe6749b}
spring.security.oauth2.client.registration.external.scope=openid,offline_access,profile
spring.security.oauth2.client.registration.external.authorization-grant-type=authorization_code


















